spring:
  profiles:
    active: local
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: gudcjfdn14@gmail.com
    password: yijqjvpyszsuckce
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
           
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/springbootblog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: 
    
mybatis:
  type-aliases-package: com.hci.blog.springboot.dto
  
custom :
  mainUri: /main/home
  siteName: HITREE  
  siteUri: http://localhost:8081
  emailFrom: no-reply@localhost
  emailFromName: HCITREE
  siteLoginUri: http://localhost:8081/member/login
  
server :
  port: 8081
  
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always
    include-binding-errors: always
    